backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Test File"
        name: "test"
        file: "test.json"
        fields:
          - {label: "Titulo", name: "title", widget: "string"}